[project]
name = "gyocas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.37.18",
    "python-dotenv>=1.0.1",
    "ruff>=0.11.2",
]
